### ISSUE TITLE
some issues about render and training

### ISSUE THREAD

**Issue by ICG0401** [ZikangXiong/MFNLF#1]
Hi, first of all, thank you for the quality of your work, which has inspired me.

In my study of your code, I have encountered a few problems. 

First, when I was testing my environment using test_envs.py, the test_render function in env.render() was working with the prompt "render() got an unexpected keyword argument ' follow'", when I delete follow, vertical, scale, it renders but the robot does not move. (gym=0.26, mujoco=2.10, mujoco_py=2.1.2.14). I don't know if you have encountered this or if you can provide me with the relevant package version so that I can solve this bug

Then, when I try to train using the code of the exps species, I get "/data/shrl/e2e/Nav/model.zip.zip'", which is probably because I didn't find the relevant file, I wonder if you could provide

Thanks a lot.

**Comment by ZikangXiong** [comment]
> render() got an unexpected keyword argument ' follow'

This is likely caused by an inconsistency between safety gym's office implementation and my adaptation. After double check, I noticed that the environment was not published in this repository, I will make some adaptations in current repository and make the code become easier to use.

If you want to do that by yourself, welcome to take a look [here](https://github.com/a-n-onymous/schrl/blob/a16dc0a07c35b4701f3cc38858a2ab0475e5ddbf/src/schrl/envs/mujoco_robots/robots/engine.py#L1491), and welcome pull request. 

> /data/shrl/e2e/Nav/model.zip.zip

This is because the pretrained models are not downloaded and the path was not set correctly. The previous pretrained models' share link is expired. To avoid a similar issue in the future, I will create a never expired link for them and add an instruction to the README. 

I will only have time to fix these issues this weekend. 

However, the above issues will not affect the training of TNLF-based policy.

**Comment by ZikangXiong** [comment]
## TODO
- [ ] Fix `follow` parameter inconsistency
- [x] Pretrained models (Download [here](https://drive.google.com/file/d/1caGcoh8eOAF3ykqnZXuvOcWOE2bHmfPb/view?usp=sharing))
- [ ] Add running instruction to README
- [x] Add dependencies to setup.py
